DROP TABLE USUARIOS;
CREATE TABLE USUARIOS
	(
	OID_U NUMBER(2), PRIMARY KEY,
	NOMBRE CHAR(10) NOT NULL,
	APELLIDOS CHAR(10) NOT NULL,
	FECHA_NACIMIENTO DATE,
	DIRECCION
	EMAIL
	TELEFONO
	DERECHOS_DE_IMAGEN
	PRIMARY KEY (),
	FOREIGN KEY () REFERENCES 
	)

DROP TABLE RELACIONES;
CREATE TABLE RELACIONES
	(
	OID_REL NUMBER(2), PRIMARY KEY,
	TIPO_DE_RELACION
	PRIMARY KEY (),
	FOREIGN KEY () REFERENCES 
	)

DROP TABLE RESPONSABLES;
CREATE TABLE RESPONSABLES
	(
	OID_R NUMBER(2), PRIMARY KEY,
	NOMBRE CHAR(10) NOT NULL,
	APELLIDOS CHAR(10) NOT NULL,
	FECHA_NACIMIENTO DATE,
	PRIMARY KEY (),
	FOREIGN KEY () REFERENCES 
	)

DROP TABLE MATRICULA;
CREATE TABLE MATRICULA
	(
	OID_M NUMBER(2), PRIMARY KEY,
	FECHA_DE_MATRICULACION DATE,
	CURSO CHAR(10) NOT NULL,
	CODIGO CHAR(10) NOT NULL,
	PRIMARY KEY (),
	FOREIGN KEY () REFERENCES 
	)

DROP TABLE FALTAS;
CREATE TABLE FALTAS
	(
	OID_F NUMBER(2), PRIMARY KEY,
	TIPO_DE_FALTA CHAR(10) NOT NULL,
	FECHA_DE_FALTA DATE,
	JUSTIFICADA CHAR(10) NOT NULL,
	PRIMARY KEY (),
	FOREIGN KEY () REFERENCES 
	)

DROP TABLE PAGOS;
CREATE TABLE PAGOS
	(
	OID_Pa NUMBER(2), PRIMARY KEY,
	FECHA_DE_PAGO DATE,
	CANTIDAD CHAR(10) NOT NULL,
	CONCEPTO CHAR(10) NOT NULL,
	ESTADO
	
	PRIMARY KEY (),
	FOREIGN KEY () REFERENCES 
	)

DROP TABLE PRESTAMOS;
CREATE TABLE PRESTAMOS
	(
	OID_P NUMBER(2), PRIMARY KEY,
	FECHA_DE_PRESTAMO DATE,
	PRIMARY KEY (),
	FOREIGN KEY () REFERENCES 
	)

DROP TABLE INSTRUMENTOS;
CREATE TABLE INSTRUMENTOS
	(
	OID_I NUMBER(2), PRIMARY KEY,
	TIPO CHAR(10) NOT NULL,
	LIBRE CHAR(10) NOT NULL,
	NOMBRE ,
	ESTADO_DE_INSTRUMENTO
	PRIMARY KEY (),
	FOREIGN KEY () REFERENCES 
	)

DROP TABLE ASIGNATURAS;
CREATE TABLE ASIGNATURAS
	(
	OID_A NUMBER(2), PRIMARY KEY,
	NOMBRE CHAR(10) NOT NULL,
	PRIMARY KEY (),
	FOREIGN KEY () REFERENCES 
	)

-- Partenecea o partenecen a ?
DROP TABLE PARTENECEA;
CREATE TABLE PARTENECEA
	(
	OID_PA NUMBER(2), PRIMARY KEY,
	PRIMARY KEY (),
	FOREIGN KEY () REFERENCES 
	)

