
DROP TABLE PERTENECEA;
DROP TABLE ASIGNATURAS;
DROP TABLE PRESTAMOS;
DROP TABLE INSTRUMENTOS;
DROP TABLE PAGOS;
DROP TABLE FALTAS;
DROP TABLE MATRICULAS;
DROP TABLE RELACIONES;
DROP TABLE RESPONSABLES;
DROP TABLE USUARIOS;

CREATE TABLE USUARIOS
	(
	OID_U NUMBER(3),
	NOMBRE VARCHAR2(50) NOT NULL,
	APELLIDOS VARCHAR2(50) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	DIRECCION VARCHAR2(60),
	EMAIL VARCHAR2(60),
	TELEFONO NUMBER(9),
	DERECHOS_DE_IMAGEN NUMBER(1),
	PRIMARY KEY (OID_U)
	);



CREATE TABLE RESPONSABLES
	(
	OID_R NUMBER(3),
	NOMBRE VARCHAR2(50) NOT NULL,
	APELLIDOS VARCHAR2(50) NOT NULL,
	TELEFONO NUMBER(9),
	EMAIL VARCHAR2(60),
	PRIMARY KEY (OID_R)
	);


CREATE TABLE RELACIONES
	(
	OID_REL NUMBER(3),
	OID_U NUMBER(3),
	OID_R NUMBER(3),
	TIPO_DE_RELACION VARCHAR2(60),
	PRIMARY KEY (OID_REL),
	FOREIGN KEY (OID_U) REFERENCES USUARIOS,
	FOREIGN KEY (OID_R) REFERENCES RESPONSABLES
	);
	

CREATE TABLE MATRICULAS
	(
	OID_M NUMBER(3),
	FECHA_DE_MATRICULACION DATE,
	CURSO INT NOT NULL,
	CODIGO INT NOT NULL,
	OID_U NUMBER(3),
	PRIMARY KEY (OID_M),
	FOREIGN KEY (OID_U) REFERENCES USUARIOS
	);


CREATE TABLE FALTAS
	(
	OID_F NUMBER(3),
	TIPO_DE_FALTA ENUM('Pago','Asistencia'),
	FECHA_DE_FALTA DATE,
	JUSTIFICADA NUMBER(1),
	OID_M NUMBER(3),
	PRIMARY KEY (OID_F),
	FOREIGN KEY (OID_M) REFERENCES MATRICULAS
	);


CREATE TABLE PAGOS
	(
	OID_Pa NUMBER(3),
	FECHA_DE_PAGO DATE,
	CANTIDAD CHAR(10) NOT NULL,
	CONCEPTO CHAR(10) NOT NULL,
	ESTADO VARCHAR2(50),
	OID_M NUMBER(3),
	PRIMARY KEY (OID_Pa),
	FOREIGN KEY (OID_M) REFERENCES MATRICULAS
	);


CREATE TABLE INSTRUMENTOS
	(
	OID_I NUMBER(3), 
	TIPO VARCHAR2(50) NOT NULL,
	LIBRE NUMBER(1),
	NOMBRE VARCHAR2(50),
	ESTADO_DE_INSTRUMENTO VARCHAR2(50),
	PRIMARY KEY (OID_I)
	);


CREATE TABLE PRESTAMOS
	(
	OID_P NUMBER(3), 
	FECHA_DEL_PRESTAMO DATE,
	OID_M NUMBER(3),
	OID_I NUMBER(3),
	PRIMARY KEY (OID_P),
	FOREIGN KEY (OID_M) REFERENCES MATRICULAS,
	FOREIGN KEY (OID_I) REFERENCES INSTRUMENTOS
	);


CREATE TABLE ASIGNATURAS
	(
	OID_A NUMBER(3), 
	NOMBRE VARCHAR2(60) NOT NULL,
	PRIMARY KEY (OID_A)
	);


CREATE TABLE PERTENECEA
	(
	OID_PA NUMBER(5),
	OID_M NUMBER(3),
	OID_A NUMBER(3), 
	PRIMARY KEY (OID_PA),
	FOREIGN KEY (OID_M) REFERENCES MATRICULAS,
	FOREIGN KEY (OID_A) REFERENCES ASIGNATURAS
	);

