DROP TABLE USUARIOS;
CREATE TABLE USUARIOS
	(
	OID_U NUMBER(2),
	NOMBRE VARCHAR2(50) NOT NULL,
	APELLIDOS VARCHAR2(50) NOT NULL,
	FECHA_NACIMIENTO DATE,
	DIRECCION VARCHAR2(60),
	EMAIL VARCHAR2(60),
	TELEFONO INT,
	DERECHOS_DE_IMAGEN BOOLEAN,
	PRIMARY KEY (OID_U),
	);

DROP TABLE RELACIONES;
CREATE TABLE RELACIONES
	(
	OID_REL NUMBER(2),
	OID_U NUMBER(2),
	OID_R NUMBER(2),
	TIPO_DE_RELACION VARCHAR2(60),
	PRIMARY KEY (OID_REL),
	FOREIGN KEY (OID_U) REFERENCES USUARIOS,
	FOREIGN KEY (OID_R) REFERENCES RESPONSABLES
	);

DROP TABLE RESPONSABLES;
CREATE TABLE RESPONSABLES
	(
	OID_R NUMBER(2),
	NOMBRE VARCHAR2(50) NOT NULL,
	APELLIDOS VARCHAR2(50) NOT NULL,
	FECHA_NACIMIENTO DATE,
	PRIMARY KEY (OID_R),
	);

DROP TABLE MATRICULA;
CREATE TABLE MATRICULA
	(
	OID_M NUMBER(2),
	FECHA_DE_MATRICULACION DATE,
	CURSO INT NOT NULL,
	CODIGO INT NOT NULL,
	OID_U NUMBER(2),
	PRIMARY KEY (OID_M),
	FOREIGN KEY (OID_U) REFERENCES USUARIOS
	);

DROP TABLE FALTAS;
CREATE TABLE FALTAS
	(
	OID_F NUMBER(2),
	TIPO_DE_FALTA CHAR(10) NOT NULL,
	FECHA_DE_FALTA DATE,
	JUSTIFICADA CHAR(10) NOT NULL,
	OID_M NUMBER(2),
	PRIMARY KEY (OID_F),
	FOREIGN KEY (OID_M) REFERENCES MATRICULA
	);

DROP TABLE PAGOS;
CREATE TABLE PAGOS
	(
	OID_Pa NUMBER(2),
	FECHA_DE_PAGO DATE,
	CANTIDAD CHAR(10) NOT NULL,
	CONCEPTO CHAR(10) NOT NULL,
	ESTADO ENUM('Pagado', 'Pendiente'),
	OID_M NUMBER(2),
	PRIMARY KEY (OID_Pa),
	FOREIGN KEY (OID_M) REFERENCES MATRICULA
	);

DROP TABLE PRESTAMOS;
CREATE TABLE PRESTAMOS
	(
	OID_P NUMBER(2), 
	FECHA_DE_PRESTAMO DATE,
	OID_M NUMBER(2),
	OID_I NUMBER(2),
	PRIMARY KEY (OID_P),
	FOREIGN KEY (OID_M) REFERENCES MATRICULA,
	FOREIGN KEY (OID_I) REFERENCES INSTRUMENTOS
	);

DROP TABLE INSTRUMENTOS;
CREATE TABLE INSTRUMENTOS
	(
	OID_I NUMBER(2), 
	TIPO VARCHAR2(50) NOT NULL,
	LIBRE BOOLEAN NOT NULL,
	NOMBRE VARCHAR2(50),
	ESTADO_DE_INSTRUMENTO ENUM('Nuevo,Usado,Deteriorado'),
	PRIMARY KEY (OID_I)
	);

DROP TABLE ASIGNATURAS;
CREATE TABLE ASIGNATURAS
	(
	OID_A NUMBER(2), 
	NOMBRE VARCHAR2(60) NOT NULL,
	PRIMARY KEY (OID_A),
	);

-- Partenecea o partenecen a ?
DROP TABLE PARTENECEA;
CREATE TABLE PARTENECEA
	(
	OID_PA NUMBER(2),
	OID_M NUMBER(2),
	OID_A NUMBER(2), 
	PRIMARY KEY (OID_PA),
	FOREIGN KEY (OID_M) REFERENCES MATRICULA,
	FOREIGN KEY (OID_A) REFERENCES ASIGNATURAS
	);

