CREATE OR REPLACE TRIGGER EDAD_USUARIOS 
BEFORE INSERT OR UPDATE OF FECHA_NACIMIENTO ON USUARIOS 
BEGIN
IF TO_DATE(:NEW.FECHA_NACIMENTO)-SYSDATE<1100
THEN raise_application_error(-20501,'Un usuario debe tener al menos 3 años');
END IF;
END;
/
